name: Deploy to Google Apps Script

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_version:
        description: 'Deploy a new version (yes/no)'
        required: false
        default: 'no'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install clasp globally
      run: npm install -g @google/clasp

    - name: Setup clasp authentication
      env:
        CLASP_CREDENTIALS: ${{ secrets.CLASP_CREDENTIALS }}
      run: |
        # claspの認証ファイルを作成
        mkdir -p ~/.clasprc
        echo "$CLASP_CREDENTIALS" > ~/.clasprc.json
        chmod 600 ~/.clasprc.json

    - name: Verify clasp setup
      run: |
        # clasp設定の確認
        if [ ! -f ".clasp.json" ]; then
          echo "Error: .clasp.json file not found"
          exit 1
        fi
        
        # スクリプトIDの確認
        SCRIPT_ID=$(cat .clasp.json | grep scriptId | cut -d'"' -f4)
        if [ -z "$SCRIPT_ID" ]; then
          echo "Error: Script ID not found in .clasp.json"
          exit 1
        fi
        echo "Script ID: $SCRIPT_ID"

    - name: Push code to Google Apps Script
      run: |
        echo "Pushing code to Google Apps Script..."
        clasp push --force

    - name: Deploy new version (if requested)
      if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_version == 'yes'
      run: |
        echo "Deploying new version..."
        DEPLOYMENT_ID=$(clasp deploy --description "GitHub Actions deployment - $(date +%Y-%m-%d_%H:%M:%S)")
        echo "Deployment completed: $DEPLOYMENT_ID"

    - name: Create deployment summary
      if: always()
      run: |
        echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- Branch: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
        echo "- Commit: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
        echo "- Triggered by: ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
        echo "- Timestamp: $(date)" >> $GITHUB_STEP_SUMMARY